title: Ocean Wave Archive
logo: /assets/img/logo.png
email: hmbaek@pusan.ac.kr
description: Ph.D. course note
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: air
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

sidebar:
  - name: Google Scholar
    icon: fa-solid fa-user-graduate
    link: https://scholar.google.com/citations?user=jaLnQNMAAAAJ
  - name: GitHub
    icon: fa-brands fa-github
    link: https://github.com/hyminb
